#############################################################################
# Makefile for building: wargame-master
# Generated by qmake (3.1) (Qt 5.15.19)
# Project:  wargame-master.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile wargame-master.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = wargame-master1.0.0
DISTDIR = /home/gbr/桌面/develop/qt/wargame-master/.tmp/wargame-master1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -pipe -O2 -flto=32 -fno-fat-lto-objects -fuse-linker-plugin -fPIC
LIBS          = $(SUBLIBS) /usr/lib/libQt5Gui.so /usr/lib/libQt5Core.so -lGL -lpthread   
AR            = gcc-ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_qmltyperegistrations.cpp \
		src/core/Geo.cpp \
		src/core/MapProvider.cpp \
		src/core/MessageBus.cpp \
		src/core/Scenario.cpp \
		src/core/SimulationEngine.cpp \
		src/core/UnitBase.cpp \
		src/units/AttackUAV.cpp \
		src/units/CommandPost.cpp \
		src/units/GroundScout.cpp \
		src/units/ReconUAV.cpp \
		src/view/ScenarioEditor.cpp \
		src/view/SimulationController.cpp \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/mocs_compilation.cpp \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp qrc_appindex_qml_module_dir_map.cpp \
		moc_MessageBus.cpp \
		moc_Scenario.cpp \
		moc_SimulationEngine.cpp \
		moc_UnitBase.cpp \
		moc_AttackUAV.cpp \
		moc_CommandPost.cpp \
		moc_GroundScout.cpp \
		moc_ReconUAV.cpp \
		moc_ScenarioEditor.cpp \
		moc_SimulationController.cpp
OBJECTS       = main.o \
		appindex_qmltyperegistrations.o \
		Geo.o \
		MapProvider.o \
		MessageBus.o \
		Scenario.o \
		SimulationEngine.o \
		UnitBase.o \
		AttackUAV.o \
		CommandPost.o \
		GroundScout.o \
		ReconUAV.o \
		ScenarioEditor.o \
		SimulationController.o \
		mocs_compilation.o \
		CMakeCXXCompilerId.o \
		qrc_appindex_qml_module_dir_map.o \
		moc_MessageBus.o \
		moc_Scenario.o \
		moc_SimulationEngine.o \
		moc_UnitBase.o \
		moc_AttackUAV.o \
		moc_CommandPost.o \
		moc_GroundScout.o \
		moc_ReconUAV.o \
		moc_ScenarioEditor.o \
		moc_SimulationController.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		wargame-master.pro src/core/Geo.h \
		src/core/MapProvider.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		src/core/SimulationEngine.h \
		src/core/UnitBase.h \
		src/units/AttackUAV.h \
		src/units/CommandPost.h \
		src/units/GroundScout.h \
		src/units/ReconUAV.h \
		src/view/ScenarioEditor.h \
		src/view/SimulationController.h main.cpp \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_qmltyperegistrations.cpp \
		src/core/Geo.cpp \
		src/core/MapProvider.cpp \
		src/core/MessageBus.cpp \
		src/core/Scenario.cpp \
		src/core/SimulationEngine.cpp \
		src/core/UnitBase.cpp \
		src/units/AttackUAV.cpp \
		src/units/CommandPost.cpp \
		src/units/GroundScout.cpp \
		src/units/ReconUAV.cpp \
		src/view/ScenarioEditor.cpp \
		src/view/SimulationController.cpp \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/mocs_compilation.cpp \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp
QMAKE_TARGET  = wargame-master
DESTDIR       = 
TARGET        = wargame-master


first: all
####### Build rules

wargame-master:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: wargame-master.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt/mkspecs/features/ltcg.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		wargame-master.pro \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/index/appindex_qml_module_dir_map.qrc
	$(QMAKE) -o Makefile wargame-master.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuthCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/link_ltcg.prf:
/usr/lib/qt/mkspecs/features/ltcg.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources_functions.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
wargame-master.pro:
build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/index/appindex_qml_module_dir_map.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile wargame-master.pro

qmake_all: FORCE


all: Makefile wargame-master

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/index/appindex_qml_module_dir_map.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/core/Geo.h src/core/MapProvider.h src/core/MessageBus.h src/core/Scenario.h src/core/SimulationEngine.h src/core/UnitBase.h src/units/AttackUAV.h src/units/CommandPost.h src/units/GroundScout.h src/units/ReconUAV.h src/view/ScenarioEditor.h src/view/SimulationController.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_qmltyperegistrations.cpp src/core/Geo.cpp src/core/MapProvider.cpp src/core/MessageBus.cpp src/core/Scenario.cpp src/core/SimulationEngine.cpp src/core/UnitBase.cpp src/units/AttackUAV.cpp src/units/CommandPost.cpp src/units/GroundScout.cpp src/units/ReconUAV.cpp src/view/ScenarioEditor.cpp src/view/SimulationController.cpp build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/mocs_compilation.cpp build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp $(DISTDIR)/
	$(COPY_FILE) --parents build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/all_aotstats.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/all_qmllint.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/all_qmllint_json.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/all_qmllint_module.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/all_qmltyperegistrations.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/appindex.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/appindex_autogen.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/appindex_autogen_timestamp_deps.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/appindex_copy_qml.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/appindex_copy_res.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/appindex_qmlimportscan.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/appindex_qmllint.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/appindex_qmllint_json.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/appindex_qmllint_module.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/appindex_qmltyperegistration.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/clean_qml_context_properties.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/dump_qml_context_properties.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/generate_qmlls_build_ini_file.dir/compiler_depend.ts build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/module_appindex_aotstats_target.dir/compiler_depend.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_appindex_qml_module_dir_map.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_appindex_qml_module_dir_map.cpp
qrc_appindex_qml_module_dir_map.cpp: build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/index/appindex_qml_module_dir_map.qrc \
		/usr/bin/rcc \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/index/C\:/Users/13857/OneDrive/Desktop/wargame-master/build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/index
	/usr/bin/rcc -name appindex_qml_module_dir_map build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/index/appindex_qml_module_dir_map.qrc -o qrc_appindex_qml_module_dir_map.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MessageBus.cpp moc_Scenario.cpp moc_SimulationEngine.cpp moc_UnitBase.cpp moc_AttackUAV.cpp moc_CommandPost.cpp moc_GroundScout.cpp moc_ReconUAV.cpp moc_ScenarioEditor.cpp moc_SimulationController.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MessageBus.cpp moc_Scenario.cpp moc_SimulationEngine.cpp moc_UnitBase.cpp moc_AttackUAV.cpp moc_CommandPost.cpp moc_GroundScout.cpp moc_ReconUAV.cpp moc_ScenarioEditor.cpp moc_SimulationController.cpp
moc_MessageBus.cpp: src/core/MessageBus.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/gbr/桌面/develop/qt/wargame-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/gbr/桌面/develop/qt/wargame-master -I/home/gbr/桌面/develop/qt/wargame-master -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/core/MessageBus.h -o moc_MessageBus.cpp

moc_Scenario.cpp: src/core/Scenario.h \
		src/core/Geo.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/gbr/桌面/develop/qt/wargame-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/gbr/桌面/develop/qt/wargame-master -I/home/gbr/桌面/develop/qt/wargame-master -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/core/Scenario.h -o moc_Scenario.cpp

moc_SimulationEngine.cpp: src/core/SimulationEngine.h \
		src/core/Geo.h \
		src/core/MapProvider.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/gbr/桌面/develop/qt/wargame-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/gbr/桌面/develop/qt/wargame-master -I/home/gbr/桌面/develop/qt/wargame-master -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/core/SimulationEngine.h -o moc_SimulationEngine.cpp

moc_UnitBase.cpp: src/core/UnitBase.h \
		src/core/Geo.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/gbr/桌面/develop/qt/wargame-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/gbr/桌面/develop/qt/wargame-master -I/home/gbr/桌面/develop/qt/wargame-master -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/core/UnitBase.h -o moc_UnitBase.cpp

moc_AttackUAV.cpp: src/units/AttackUAV.h \
		src/core/UnitBase.h \
		src/core/Geo.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/gbr/桌面/develop/qt/wargame-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/gbr/桌面/develop/qt/wargame-master -I/home/gbr/桌面/develop/qt/wargame-master -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/units/AttackUAV.h -o moc_AttackUAV.cpp

moc_CommandPost.cpp: src/units/CommandPost.h \
		src/core/UnitBase.h \
		src/core/Geo.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/gbr/桌面/develop/qt/wargame-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/gbr/桌面/develop/qt/wargame-master -I/home/gbr/桌面/develop/qt/wargame-master -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/units/CommandPost.h -o moc_CommandPost.cpp

moc_GroundScout.cpp: src/units/GroundScout.h \
		src/core/UnitBase.h \
		src/core/Geo.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/gbr/桌面/develop/qt/wargame-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/gbr/桌面/develop/qt/wargame-master -I/home/gbr/桌面/develop/qt/wargame-master -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/units/GroundScout.h -o moc_GroundScout.cpp

moc_ReconUAV.cpp: src/units/ReconUAV.h \
		src/core/UnitBase.h \
		src/core/Geo.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/gbr/桌面/develop/qt/wargame-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/gbr/桌面/develop/qt/wargame-master -I/home/gbr/桌面/develop/qt/wargame-master -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/units/ReconUAV.h -o moc_ReconUAV.cpp

moc_ScenarioEditor.cpp: src/view/ScenarioEditor.h \
		src/core/Scenario.h \
		src/core/Geo.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/gbr/桌面/develop/qt/wargame-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/gbr/桌面/develop/qt/wargame-master -I/home/gbr/桌面/develop/qt/wargame-master -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/view/ScenarioEditor.h -o moc_ScenarioEditor.cpp

moc_SimulationController.cpp: src/view/SimulationController.h \
		src/core/SimulationEngine.h \
		src/core/Geo.h \
		src/core/MapProvider.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/gbr/桌面/develop/qt/wargame-master/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/gbr/桌面/develop/qt/wargame-master -I/home/gbr/桌面/develop/qt/wargame-master -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-pc-linux-gnu -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/16/include -I/usr/local/include -I/usr/include src/view/SimulationController.h -o moc_SimulationController.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp src/view/SimulationController.h \
		src/core/SimulationEngine.h \
		src/core/Geo.h \
		src/core/MapProvider.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		src/view/ScenarioEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

appindex_qmltyperegistrations.o: build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_qmltyperegistrations.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appindex_qmltyperegistrations.o build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_qmltyperegistrations.cpp

Geo.o: src/core/Geo.cpp src/core/Geo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Geo.o src/core/Geo.cpp

MapProvider.o: src/core/MapProvider.cpp src/core/MapProvider.h \
		src/core/Geo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MapProvider.o src/core/MapProvider.cpp

MessageBus.o: src/core/MessageBus.cpp src/core/MessageBus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MessageBus.o src/core/MessageBus.cpp

Scenario.o: src/core/Scenario.cpp src/core/Scenario.h \
		src/core/Geo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scenario.o src/core/Scenario.cpp

SimulationEngine.o: src/core/SimulationEngine.cpp src/core/SimulationEngine.h \
		src/core/Geo.h \
		src/core/MapProvider.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		src/core/UnitBase.h \
		src/units/CommandPost.h \
		src/units/ReconUAV.h \
		src/units/AttackUAV.h \
		src/units/GroundScout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SimulationEngine.o src/core/SimulationEngine.cpp

UnitBase.o: src/core/UnitBase.cpp src/core/UnitBase.h \
		src/core/Geo.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		src/units/CommandPost.h \
		src/units/ReconUAV.h \
		src/units/AttackUAV.h \
		src/units/GroundScout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UnitBase.o src/core/UnitBase.cpp

AttackUAV.o: src/units/AttackUAV.cpp src/units/AttackUAV.h \
		src/core/UnitBase.h \
		src/core/Geo.h \
		src/core/MessageBus.h \
		src/core/Scenario.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AttackUAV.o src/units/AttackUAV.cpp

CommandPost.o: src/units/CommandPost.cpp src/units/CommandPost.h \
		src/core/UnitBase.h \
		src/core/Geo.h \
		src/core/MessageBus.h \
		src/core/Scenario.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CommandPost.o src/units/CommandPost.cpp

GroundScout.o: src/units/GroundScout.cpp src/units/GroundScout.h \
		src/core/UnitBase.h \
		src/core/Geo.h \
		src/core/MessageBus.h \
		src/core/Scenario.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GroundScout.o src/units/GroundScout.cpp

ReconUAV.o: src/units/ReconUAV.cpp src/units/ReconUAV.h \
		src/core/UnitBase.h \
		src/core/Geo.h \
		src/core/MessageBus.h \
		src/core/Scenario.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ReconUAV.o src/units/ReconUAV.cpp

ScenarioEditor.o: src/view/ScenarioEditor.cpp src/view/ScenarioEditor.h \
		src/core/Scenario.h \
		src/core/Geo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScenarioEditor.o src/view/ScenarioEditor.cpp

SimulationController.o: src/view/SimulationController.cpp src/view/SimulationController.h \
		src/core/SimulationEngine.h \
		src/core/Geo.h \
		src/core/MapProvider.h \
		src/core/MessageBus.h \
		src/core/Scenario.h \
		src/core/UnitBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SimulationController.o src/view/SimulationController.cpp

mocs_compilation.o: build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/mocs_compilation.cpp build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/PRMOGMWJPH/moc_MessageBus.cpp \
		src/core/MessageBus.h \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/PRMOGMWJPH/moc_Scenario.cpp \
		src/core/Scenario.h \
		src/core/Geo.h \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/PRMOGMWJPH/moc_SimulationEngine.cpp \
		src/core/SimulationEngine.h \
		src/core/MapProvider.h \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/PRMOGMWJPH/moc_UnitBase.cpp \
		src/core/UnitBase.h \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/EVYFCUPIQL/moc_AttackUAV.cpp \
		src/units/AttackUAV.h \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/EVYFCUPIQL/moc_CommandPost.cpp \
		src/units/CommandPost.h \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/EVYFCUPIQL/moc_GroundScout.cpp \
		src/units/GroundScout.h \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/EVYFCUPIQL/moc_ReconUAV.cpp \
		src/units/ReconUAV.h \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/3JYSCEOBDA/moc_ScenarioEditor.cpp \
		src/view/ScenarioEditor.h \
		build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/3JYSCEOBDA/moc_SimulationController.cpp \
		src/view/SimulationController.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mocs_compilation.o build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/appindex_autogen/mocs_compilation.cpp

CMakeCXXCompilerId.o: build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CMakeCXXCompilerId.o build/Desktop_Qt_6_11_1_MinGW_64_bit_Debug/CMakeFiles/3.30.5/CompilerIdCXX/CMakeCXXCompilerId.cpp

qrc_appindex_qml_module_dir_map.o: qrc_appindex_qml_module_dir_map.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_appindex_qml_module_dir_map.o qrc_appindex_qml_module_dir_map.cpp

moc_MessageBus.o: moc_MessageBus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MessageBus.o moc_MessageBus.cpp

moc_Scenario.o: moc_Scenario.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Scenario.o moc_Scenario.cpp

moc_SimulationEngine.o: moc_SimulationEngine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SimulationEngine.o moc_SimulationEngine.cpp

moc_UnitBase.o: moc_UnitBase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UnitBase.o moc_UnitBase.cpp

moc_AttackUAV.o: moc_AttackUAV.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AttackUAV.o moc_AttackUAV.cpp

moc_CommandPost.o: moc_CommandPost.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CommandPost.o moc_CommandPost.cpp

moc_GroundScout.o: moc_GroundScout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GroundScout.o moc_GroundScout.cpp

moc_ReconUAV.o: moc_ReconUAV.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ReconUAV.o moc_ReconUAV.cpp

moc_ScenarioEditor.o: moc_ScenarioEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ScenarioEditor.o moc_ScenarioEditor.cpp

moc_SimulationController.o: moc_SimulationController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SimulationController.o moc_SimulationController.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

